const arr = [
  {
    id: 1,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 2,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 3,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 4,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 5,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 6,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 7,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 8,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 9,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 10,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 11,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 12,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 13,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 14,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 15,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 16,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 17,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 18,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 19,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 20,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 21,
    title: "Admins",
    roles: ["Goods delivery", "Calls to clients"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 22,
    title: "General Manager",
    roles: ["Billing", "Application processing"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 23,
    title: "Manager - Tech",
    roles: ["Application processing", "Working with documentaries"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 24,
    title: "Manager - Billing",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
  {
    id: 25,
    title: "Manager - Tech",
    roles: ["Administration", "User"],
    accessright: ["Billing", "Admin", "User"],
  },
];
export function dataGroup() {
  return arr;
}
